### ISSUE TITLE
Bug: If the client has night time music enabled, no music plays in the Aether if on a server.

### ISSUE THREAD

**Issue by nocturni** [The-Aether-Team/The-Aether-Genesis#204]
### What Feature Types Apply to This Bug?

Audio, Config

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

Neoforge 47.1.105

### The Aether Genesis Version

1.20.1-0.0.1

### Is This Bug a Conflict With Another Mod?

I had the Redux addon installed, but it does not seem to be the problem.

### Steps to Reproduce

1. Have The Aether: Genesis installed on both client and server
2. Join a server with night time music enabled on clientside
3. No music plays in the dimension, whether daytime or nighttime

### What You Expect To Happen

Music is expected to play during the day or the night

### What Actually Happened

Music does not play at all

### Additional Details

Using the Sound Manager mod, I tried forcing music to play every 3 seconds, it worked in the Overworld but nothing happened in the Aether except in singleplayer.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Zepalesque** [comment]
it’s actually fairly possible this may be a redux issue, it decreases the time between music tracks and has a system to cancel overlapping music tracks (as decreasing the delay causes this oddly)
It’s possible I may have made some oversight in the system that causes it to not work properly on servers, though that’d be strange since it’s supposed to all be client-side

can you check the logs for either of these two errors?
`Caught music track that seems to not belong in the Aether trying to play! Sound ID: [???]`

`Caught potential overlapping music track attempting to play in the Aether! Sound ID: [???]`
If so, and the sound id is one of the aether music tracks, then this is very likely a Redux issue, and it’d be helpful if you reported it on its issue tracker so I can remember to fix it lol
here’s the repository:
https://github.com/Zepalesque/The-Aether-Redux/issues

**Comment by nocturni** [comment]
closing this... it seems like i was really unlucky during my tests and music just didn't play for some reason, the errors do indeed appear, moving to the Redux repo
